source 'https://rubygems.org'

ruby "2.2.0"

gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass'
gem 'bcrypt'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'thin'
gem 'unicorn'
gem 'vacuum'
gem 'rails_12factor', group: :production


group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
end

group :test do
  gem 'faker'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'turnip'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

